stages:
  - build
  - publish
  - deploy-dev
  - deploy-prod
#variables: 
  # APPVER: $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA

build:
  stage: build
  image:
    name: golang:1.13.1
  script:
    - go build -o main main.go
  artifacts:
    paths:
      - main
  variables:
    CGO_ENABLED: 0

publish:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  dependencies:
    - build  
  only:
    - main

deploy-dev:
  stage: deploy-dev
  image: alpine:3.11
  before_script:
    - apk add --no-cache git curl bash
    - apk add py3-pip
    - pip3 install yq
    - apk add --upgrade jq
    - git remote set-url origin https://${CI_USERNAME}:${CI_PUSH_TOKEN}@gitlab.com/manarkhemakhem0/gitops-webapp-master.git
    - git config --global user.email "gitlab@gitlab.com"
    - git config --global user.name "GitLab CI/CD"
  script:
    - git checkout -B master
    - git pull origin master
   # - yq -yi --arg appVersion "$APPVER" '.appVersion |= $appVersion' gitops-webapp-chart/Chart.yaml
   # - cat gitops-webapp-chart/Chart.yaml
    - yq -yi --arg tag "$CI_COMMIT_SHA" '.image.tag |= $tag' gitops-webapp-chart/values-dev.yaml
    - cat gitops-webapp-chart/values-dev.yaml
    - git commit -am '[skip ci] DEV image update'
    - git push origin master
  only:
    - main

deploy-prod:
  stage: deploy-prod
  image: alpine:3.11
  before_script:
    - apk add --no-cache git curl bash
    - apk add py3-pip
    - pip3 install yq
    - apk add --upgrade jq
    - git remote set-url origin https://${CI_USERNAME}:${CI_PUSH_TOKEN}@gitlab.com/manarkhemakhem0/gitops-webapp-master.git
    - git config --global user.email "gitlab@gitlab.com"
    - git config --global user.name "GitLab CI/CD"
  script:
    - git checkout -B master
    - git pull origin master
   # - yq -yi --arg appVersion "$APPVER" '.appVersion |= $appVersion' gitops-webapp-chart/Chart.yaml
   # - cat gitops-webapp-chart/Chart.yaml
    - yq -yi --arg tag "$CI_COMMIT_SHA" '.image.tag |= $tag' gitops-webapp-chart/values-prod.yaml
    - cat gitops-webapp-chart/values-prod.yaml
    - git commit -am '[skip ci] PROD image update'
    - git push origin master
  only:
    - main
  when: manual
