---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-dev
  namespace: argocd
spec:
  project: default
  source: 
    helm:
      valueFiles:
      - values-dev.yaml
    repoURL: https://gitlab.com/manarkhemakhem0/gitops-webapp.git
    targetRevision: HEAD
    path: gitops-webapp-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-prod
  namespace: argocd
spec:
  project: default
  source: 
    helm:
      valueFiles:
      - values-prod.yaml
    repoURL: https://gitlab.com/manarkhemakhem0/gitops-webapp.git
    targetRevision: HEAD
    path: gitops-webapp-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true